# Generated by Django 3.1 on 2020-08-15 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_trip_tripitinerary_trippicture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='endDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='startDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
